/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//#include "STM32F103x8.h"
//#include "stm32f103x8_gpio_driver.h"
#include "LM35.h"
#include "ldr.h"
#include "Rain_Sensor.h"
#include"DC_MOTOR.h"
#include"SYSTICK.h"
#include"CAN.h"
#include"stm32f103x8_USART_driver.h"
#define RECIEVED_ID_BY_ECU1   1
#define ENABLE_RAIN_DETECTION  1

uint8_t flag=1;

void checkForFirmwareUpdate()
{
	if(HAL_CAN_GetRxFifoFillLevel(CAN_FILTER_FIFO0))
	{
		CAN_RxHeaderTypeDef cfg;

		uint8_t data[8];

		HAL_CAN_GetRxMessage(CAN_FILTER_FIFO0, &cfg, data);
		flag=1;
	}

}

uint16_t Rain=0;//PA3(CH3)
uint16_t room_temp=0, liquid_temp=0;//PA0(CH0), PA1(CH1)
uint16_t ldr=0;//PA2(CH2)


void delay_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_GPIOC_CLK_EN();


	/*enable clocks for periphrals*/
	RCC_ADC_CLK_EN();
	RCC_AFIO_CLK_EN();
	RCC_USART1_CLK_EN();


	/*init periphrals*/
	CAN_InitTypeDef cfg = {1, CAN_MODE_NORMAL, 1, 6, 1, 0, 0, 0, 0, 0, 0};
	CAN_Init(&cfg);

	Init_temp();
	Init_ldr();
	Init_Rain();
	DcMotor1_Init();
	DcMotor2_Init();

	UART_Config UART_1 = {UART_MODE_TX, UART_BaudRate_57600,UART_Payload_Length_8B, UART_Parity__NONE, UART_StopBits__1, UART_IRQ_Enable_NONE, NULL};
	MCAL_UART_Init(USART1, &UART_1);

	MCAL_UART_GPIO_Set_Pins(USART1);
	/*remaining water level sensor*/

	uint8_t sensors_data_arr[4]={0};

	while (1)
	{

		room_temp=Read_Temp(CH_0);
		sensors_data_arr[0] = room_temp;
		MCAL_UART_SendData(USART1, &room_temp, enable);

		/*liquid_temp=Read_Temp(CH_1);
		sensors_data_arr[1] = liquid_temp;
		 */
		delay_ms(10);

		ldr=Read_ldr(CH_2);
		sensors_data_arr[1] = ldr;
		MCAL_UART_SendData(USART1, &ldr, enable);

		delay_ms(10);

		Rain=Read_Rain(CH_3);
		MCAL_UART_SendData(USART1, &Rain, enable);


		/*if update recieved*/
		if(flag == 1)
		{
			Rain=Read_Rain(CH_3);
			sensors_data_arr[3] = Rain;

			if(Rain >= 50)
			{
				/*turn on wipers*/
				DC_MOTOR1_setSpeed(1000, clkWise);
				/*delay*/
				delay_ms(2000);
				DC_MOTOR1_setSpeed(0, clkWise);
				delay_ms(2000);
				DC_MOTOR1_setSpeed(1000, antiClkWise);
				/*delay*/
				delay_ms(2000);
				DC_MOTOR1_setSpeed(0, clkWise);
				delay_ms(2000);
				DC_MOTOR1_setSpeed(1000, clkWise);
				delay_ms(2000);

			}
			else
			{
				DC_MOTOR1_setSpeed(0, clkWise);
			}
		}


		/*check temp and turn on dc motor*/
		if(room_temp > 30)
		{
			DC_MOTOR2_setSpeed(60000, clkWise);
		}
		else if(room_temp <=30)
		{
			DC_MOTOR2_setSpeed(0, clkWise);

		}

	}
}
